package com.mpcorp.identity.infrastructures.persistence.jpa_entity

import jakarta.persistence.*
import java.sql.Timestamp
import java.util.UUID

/**
 * UserSessionJpaEntity — tracks active device sessions for a user.
 *
 * Each login creates/updates a session record keyed by (userId, deviceId).
 * Allows the user to view and revoke individual device sessions (GDPR UX).
 *
 * deviceId is generated by the client (Flutter: UUID stored in FlutterSecureStorage).
 */
@Entity
@Table(
    name = "user_session",
    uniqueConstraints = [UniqueConstraint(columnNames = ["user_id", "device_id"])],
)
class UserSessionJpaEntity(

    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    var id: UUID? = null,

    @Column(name = "user_id", nullable = false)
    var userId: UUID,

    @Column(name = "device_id", nullable = false, length = 128)
    var deviceId: String,

    @Column(name = "device_name", length = 255)
    var deviceName: String? = null,

    @Column(name = "device_platform", length = 32)
    var devicePlatform: String? = null,

    @Column(name = "last_seen", nullable = false)
    var lastSeen: Timestamp,

    @Column(name = "created_at", nullable = false)
    var createdAt: Timestamp,

    @Column(name = "is_active", nullable = false)
    var isActive: Boolean = true,

    // JWT token hash (sha256) for quick revocation check — not the full token
    @Column(name = "token_hash", length = 64)
    var tokenHash: String? = null,
)
