package com.mpcorp.identity.infrastructures.fabric

import io.grpc.Grpc
import io.grpc.ManagedChannel
import io.grpc.TlsChannelCredentials
import org.hyperledger.fabric.client.Gateway
import org.hyperledger.fabric.client.identity.*
import org.springframework.boot.context.properties.EnableConfigurationProperties
import org.springframework.context.annotation.Bean
import org.springframework.context.annotation.Configuration
import java.io.File
import java.io.FileReader
import java.security.PrivateKey
import java.security.cert.X509Certificate

/**
 * Configures the Hyperledger Fabric Gateway connection.
 *
 * Uses gRPC + TLS to connect to peer0.org1.example.com:7051.
 * Identity is read from the User1 MSP material generated by cryptogen.
 */
@Configuration
@EnableConfigurationProperties(FabricProperties::class)
class FabricGatewayConfig(private val props: FabricProperties) {

    @Bean(destroyMethod = "close")
    fun fabricGateway(): Gateway {
        val channel = newGrpcConnection()
        val identity = newIdentity()
        val signer = newSigner()

        return Gateway.newInstance()
            .identity(identity)
            .signer(signer)
            .connection(channel)
            // Timeouts suitable for a local dev network
            .evaluateOptions { opts -> opts.withDeadlineAfter(5, java.util.concurrent.TimeUnit.SECONDS) }
            .endorseOptions { opts -> opts.withDeadlineAfter(15, java.util.concurrent.TimeUnit.SECONDS) }
            .submitOptions { opts -> opts.withDeadlineAfter(15, java.util.concurrent.TimeUnit.SECONDS) }
            .commitStatusOptions { opts -> opts.withDeadlineAfter(60, java.util.concurrent.TimeUnit.SECONDS) }
            .connect()
    }

    /* ── private helpers ─────────────────────────────────────────────────── */

    private fun newGrpcConnection(): ManagedChannel {
        val tlsCertFile = resolveFile(props.peer.tlsCertPath)
        val tlsCreds = TlsChannelCredentials.newBuilder()
            .trustManager(tlsCertFile)
            .build()

        // peer0.org1 registers itself as "peer0.org1.example.com" on the TLS cert
        return Grpc.newChannelBuilder(props.peer.endpoint, tlsCreds)
            .overrideAuthority("peer0.org1.example.com")
            .build()
    }

    private fun newIdentity(): X509Identity {
        val certFile = resolveFile(props.gateway.certPath)
        val cert: X509Certificate = Identities.readX509Certificate(FileReader(certFile))
        return X509Identity(props.mspId, cert)
    }

    private fun newSigner(): Signer {
        val keyDir = resolveFile(props.gateway.keyPath)
        // keystore directory contains a single .pem private key file
        val keyFile = if (keyDir.isDirectory) {
            keyDir.listFiles { f -> f.extension == "pem" || f.name.endsWith("_sk") }
                ?.firstOrNull()
                ?: throw IllegalStateException("No private key found in ${keyDir.absolutePath}")
        } else {
            keyDir
        }
        val privateKey: PrivateKey = Identities.readPrivateKey(FileReader(keyFile))
        return Signers.newPrivateKeySigner(privateKey)
    }

    private fun resolveFile(path: String): File {
        val file = File(path)
        if (!file.exists()) {
            throw IllegalStateException("Fabric file/directory not found: $path (check application.yml paths)")
        }
        return file
    }
}
